import turtle
def drawText(ch):
    turtle.pendown()
    if ch=='ㅂ':
        turtle.setheading(-90)
        turtle.forward(100)
        turtle.setheading(0)
        turtle.forward(80)
        turtle.setheading(90)
        turtle.forward(100)
        turtle.penup()
        turtle.backward(50)
        turtle.pendown()
        turtle.setheading(180)
        turtle.forward(80)
    elif ch=='ㅏ':
        turtle.setheading(-90)
        turtle.forward(120)
        turtle.penup()
        turtle.backward(60)
        turtle.pendown()
        turtle.setheading(0)
        turtle.forward(30)
    elif ch=='ㄱ':
        turtle.setheading(0)
        turtle.forward(100)
        turtle.setheading(-90)
        turtle.forward(50)
    elif ch=='ㅈ':
        turtle.setheading(0)
        turtle.forward(100)
        turtle.setheading(-140)
        turtle.forward(120)
        turtle.penup()
        turtle.backward(60)
        turtle.setheading(-40)
        turtle.pendown()
        turtle.forward(120/2)
    elif ch=='ㅜ':
        turtle.setheading(0)
        turtle.forward(120)
        turtle.penup()
        turtle.backward(60)
        turtle.setheading(-90)
        turtle.pendown()
        turtle.forward(40)
    elif ch=='ㄴ':
        turtle.setheading(-90)
        turtle.forward(50)
        turtle.setheading(0)
        turtle.forward(100)
    elif ch=='ㅇ':
        turtle.setheading(0)
        turtle.circle(35)
    elif ch =='ㅕ':
        turtle.setheading(-90)
        turtle.forward(120)
        turtle.penup()
        turtle.backward(50)
        turtle.setheading(180)
        turtle.pendown()
        turtle.forward(30)
        turtle.penup()
        turtle.backward(30)
        turtle.setheading(90)
        turtle.forward(20)
        turtle.setheading(180)
        turtle.pendown()
        turtle.forward(30)
    turtle.penup()

turtle.penup()
turtle.goto(-300, 300)
drawText('ㅂ')
turtle.goto(-180, 310)
drawText('ㅏ')
turtle.goto(-280, 180)
drawText('ㄱ')
turtle.goto(-100,300)
drawText('ㅈ')
turtle.goto(-110, 200)
drawText('ㅜ')
turtle.goto(-100,180)
drawText('ㄴ')
turtle.goto(90, 230)
drawText('ㅇ')
turtle.goto(170,315)
drawText('ㅕ')
turtle.goto(110, 130)
drawText('ㅇ')

turtle.exitonclick()
